Add a tutorial for production on Winbloat
Scratch-Client-4/itchy-ionic pull request #20
Opened 2021-02-15 14:14 UTC by monitrr

This PR adds a tutorial for production on Winbloat.

2021-02-15 17:13 UTC, locness3 commented
Is npx really needed in  this case? O_o
Also using npx works on Linux, so you can just straight up change the package.json

2021-02-16 11:35 UTC, Semisol requested changes
Instead of putting the package.json inside the README, it should be its own file `package.windows.json`, or even better: Use something to detect the environment and run based off of that.

2021-02-16 11:58 UTC, locness3 commented
> Instead of putting the package.json inside the README, it should be its own file `package.windows.json`, or even better: Use something to detect the environment and run based off of that.

Even better! The modifified package.json should w/o problems on linux *and macOS* ;)

2021-02-16 12:01 UTC, Semisol commented
> > Instead of putting the package.json inside the README, it should be its own file `package.windows.json`, or even better: Use something to detect the environment and run based off of that.
> 
> Even better! The modifified package.json should w/o problems on linux _and macOS_ ;)

Yeah

2021-02-16 12:13 UTC, Semisol requested changes
Oops, review removed

2021-03-18 18:07 UTC, micahlt requested changes

2021-03-18 18:07 UTC, micahlt commented on README.md
> +
Unfortunately this is _extremely_ unreliable as dependencies change very often.  I can't merge this with this approach.

2021-03-19 16:07 UTC, locness3 commented
JUST USE npx IN THE REGULAR PACKAGE.JSON

2021-03-20 12:07 UTC, Semisol requested changes
Just add the npx script to the package.json, it does not need to be changed

2021-08-01 22:44 UTC, closed without merging